--- # 默认.config调整系统
patchs:
- patch:
    #used: no
    path: /.config
    items:
    - name: 禁用所有目标平台
      cfgs: [
        CONFIG_TARGET_ppc40x=n,
        CONFIG_TARGET_realview=n,
        CONFIG_TARGET_arm64=n,
        CONFIG_TARGET_sunxi=n,
        CONFIG_TARGET_atheros=n,
        CONFIG_TARGET_ar71xx=n,
        CONFIG_TARGET_at91=n,
        CONFIG_TARGET_avr32=n,
        CONFIG_TARGET_brcm2708=n,
        CONFIG_TARGET_bcm53xx=n,
        CONFIG_TARGET_brcm47xx=n,
        CONFIG_TARGET_brcm63xx=n,
        CONFIG_TARGET_netlogic=n,
        CONFIG_TARGET_cns21xx=n,
        CONFIG_TARGET_cns3xxx=n,
        CONFIG_TARGET_octeon=n,
        CONFIG_TARGET_ep93xx=n,
        CONFIG_TARGET_cobalt=n,
        CONFIG_TARGET_gemini=n,
        CONFIG_TARGET_mpc52xx=n,
        CONFIG_TARGET_mpc83xx=n,
        CONFIG_TARGET_mpc85xx=n,
        CONFIG_TARGET_imx6=n,
        CONFIG_TARGET_mxs=n,
        CONFIG_TARGET_adm8668=n,
        CONFIG_TARGET_adm5120=n,
        CONFIG_TARGET_xburst=n,
        CONFIG_TARGET_ixp4xx=n,
        CONFIG_TARGET_lantiq=n,
        CONFIG_TARGET_malta=n,
        CONFIG_TARGET_mvebu=n,
        CONFIG_TARGET_kirkwood=n,
        CONFIG_TARGET_orion=n,
        CONFIG_TARGET_pxa=n,
        CONFIG_TARGET_rb532=n,
        CONFIG_TARGET_mcs814x=n,
        CONFIG_TARGET_oxnas=n,
        CONFIG_TARGET_ipq806x=n,
        CONFIG_TARGET_au1000=n,
        CONFIG_TARGET_ramips=n,
        CONFIG_TARGET_ar7=n,
        CONFIG_TARGET_omap=n,
        CONFIG_TARGET_uml=n,
        CONFIG_TARGET_x86=n,
        CONFIG_TARGET_x86_64=n,
      ]
      mode: config
    - name: 启用ramips平台
      cfgs: [
        CONFIG_TARGET_ramips=y,
        CONFIG_TARGET_ramips_mt7620=y,
      ]
      mode: config
- patch:
    path: /target/linux/ramips/image/Makefile
    items:
    - name: 增加自定义设备MTALL(3) 增加64MB设备编译函数
      orig: !!str
        "BuildFirmware/Default16M/initramfs=$(call BuildFirmware/OF/initramfs,$(1),$(2),$(3),$(4))\n\n"
      fix: !!str
        "ralink_default_fw_size_64M=66453504\n\
        BuildFirmware/Default64M/squashfs=$(call BuildFirmware/OF,$(1),$(2),$(3),$(ralink_default_fw_size_64M),$(4))\n\
        BuildFirmware/Default64M/initramfs=$(call BuildFirmware/OF/initramfs,$(1),$(2),$(3),$(4))\n\n"
      mode: add
    - name: 增加自定义设备MTALL(3) 增加32MB设备编译函数
      orig: !!str
        "BuildFirmware/Default16M/initramfs=$(call BuildFirmware/OF/initramfs,$(1),$(2),$(3),$(4))\n\n"
      fix: !!str
        "ralink_default_fw_size_32M=32899072\n\
        BuildFirmware/Default32M/squashfs=$(call BuildFirmware/OF,$(1),$(2),$(3),$(ralink_default_fw_size_32M),$(4))\n\
        BuildFirmware/Default32M/initramfs=$(call BuildFirmware/OF/initramfs,$(1),$(2),$(3),$(4))\n\n"
      mode: add
- patch:
    #path: /.config
    path: [
      /target/linux/ramips/mt7620/config-3.14,
      /target/linux/ramips/mt7620/config-3.18,
      /target/linux/ramips/mt7620/config-default,
    ]
    items:
    - name: 内核MMC/SD卡支持(mt7620)
      cfgs: [
        CONFIG_PACKAGE_kmod-sdhci=n,
        CONFIG_PACKAGE_kmod-sdhci-mt7620=n,
        CONFIG_PACKAGE_kmod-mmc-over-gpio=n,
      ]
      mode: config
- patch:
    path: /target
    items:
    - name: 32MB-Reboot 补丁
      base: /target/linux/ramips/
      orig: [
        {
          src: patches/9999-a-reg-shutdown-fix-32MB-reboot.3.14.patch,
          dst: patches-3.14/9999-fix-32MB-reboot-by-Manfeel.patch
        },
        {
          src: patches/9999-a-reg-shutdown-fix-32MB-reboot.3.18.patch,
          dst: patches-3.18/9999-a-fix-32MB-reboot-by-Manfeel.patch
        },
      ]
      mode: copy,#debug
- patch:
    path: /target
    items:
    - name: MMC 写使能 补丁
      base: /target/linux/ramips/
      orig: [
        {
          src: patches/9002-SD-sdhci-mt7620-gpio-disable-MMC-WriteProtection.patch,
          dst: patches-3.14/9002-SD-sdhci-mt7620-gpio-disable-MMC-WriteProtection-by-Manfeel.patch
        },
        {
          src: patches/9002-SD-sdhci-mt7620-gpio-disable-MMC-WriteProtection.patch,
          dst: patches-3.18/9002-SD-sdhci-mt7620-gpio-disable-MMC-WriteProtection-by-Manfeel.patch
        },
      ]
      mode: copy,#debug
- patch:
    #path: /.config
    path: /target/linux/ramips/dts/mt7620a.dtsi
    items:
    - name: 打开两个spi(mt7620)
      orig: !!str
        "\t\tspi_pins: spi {\n\
        \t\t\tspi {\n\
        \t\t\t\tralink,group = \"spi\";\n\
        \t\t\t\tralink,function = \"spi\";\n\
        \t\t\t};\n\
        \t\t};\n"
      fix: !!str
        "\t\tspi_pins: spi {\n\
        \t\t\tspi {\n\
        \t\t\t\tralink,group = \"spi\";\n\
        \t\t\t\tralink,function = \"spi\";\n\
        \t\t\t};\n\
        \t\t\t/* added by manfeel */\n\
        \t\t\tcs1 {\n\
        \t\t\t\tralink,group = \"spi refclk\";\n\
        \t\t\t\tralink,function = \"spi refclk\";\n\
        \t\t\t};\n\
        \t\t};\n"
      mode: std+